### PR TITLE
removed pandas warning

### PR DESCRIPTION
**Pull request by ncfirth**
Just a couple of lines to change in the end.

### CODE REVIEW

**Comment by beOn** [comment]
Thank you!

**Comment by harrisonford** [comment]
Nice ! 👍  Is this also updated on the pypi or not yet?

**Comment by beOn** [comment]
Bit by bit. Working through the other test failures.

**Comment by beOn** [comment]
Okay, I'll push an update to pypi shortly.

**Comment by harrisonford** [comment]
Cool, tell me when you push it and I'll test it out ;)

**Pull request merged**
