### PR TITLE
Changed `units` calling in `extract_events`, added some unit tests.

### PR DESCRIPTION
**Pull request by tomwallis**
I didn’t understand the need for the upper case TIME_UNITS or
SAMPLE_UNITS and the docs for calling them were confusing. I think this is simpler.

### CODE REVIEW

**Comment by tomwallis** [comment]
Since I'm not very experienced with Pull Requests, I didn't realise that the unit tests I added in [this commit](https://github.com/tomwallis/cili/commit/cc34255b98cccd0cb5970c956b361e234fa60b06) would be tacked onto this pull request. Unfortunately this gets a bit confusing: the pull request is now about both changing how `units` are specified and also a couple of unit tests.

**Comment by beOn** [comment]
Awesome - thank you! This is a great start. I'm going to give it a more careful look over the weekend, make some adjustments, and pull it into a dev branch.

At some point I want to get an exhaustive set of test data files - when you have a chance, please rename your data file something that indicates frequency and mon/bi-nocularity.

More soon - thanks again!

**Comment by tomwallis** [comment]
Ok, I've renamed the data files to include binoc / sampling info, and also the "ground truth" data files to be consistent.

**Comment by beOn** [comment]
Yarg, I haven't touched this yet, and it'll be a few days yet before I have time.

**Pull request merged**
